%% OFDM Radar w/ Default Parameters
radar = ofdmRadar(...
    'nDataCarriers', 49,...
    'targetVelocity',50,...
    'nullDcSubcarrier', false);
radar.run();

%% OFDM Radar PSLR Measurement
f = 5.9e9;
c = physconst('lightspeed');
lambda = c/f;
sampleRate = 10e6;
PRI = 84/sampleRate;
PRF = 1/PRI;
unambigVelocity = PRF*lambda/4;
targetVelocity = -100:10:100; %(-128:4:127)*unambigVelocity/128;
PSLR_dB = zeros(size(targetVelocity));

for i = 1:length(PSLR_dB)
    radar = ofdmRadar(...
        'nDataCarriers', 49,...
        'targetVelocity', targetVelocity(i),...
        'nullDcSubcarrier', false, ...
        'plotResults', false,...
        'SNR_dB', 200,...
        'numPulses', 256);
    radar.run();
    PSLR_dB(i) = radar.measurePSLR();
end

figure(1)
clf;
plot(targetVelocity, PSLR_dB, LineWidth=1.5);


 % Label Plot
            title('Peak Sidelobe Ratio vs Velocity')
            %legend('Signal Power', 'Average Power');
            xlabel('Velocity (m/s)');
            ylabel('PSLR (dB)');
             grid on;
            linewidth(1.5);

%% OFDM Radar PSLR Measurement
f = 5.9e9;
c = physconst('lightspeed');
lambda = c/f;
sampleRate = 10e6;
PRI = 84/sampleRate;
unambigRange = c*PRI/2;
targetRange = linspace(0,unambigRange,20);
PSLR_dB = zeros(size(targetRange));

for i = 1:length(PSLR_dB)
    radar = ofdmRadar(...
        'nDataCarriers', 49,...
        'targetRange', targetRange(i),...
        'targetVelocity', 0,...
        'nullDcSubcarrier', false, ...
        'plotResults', false,...
        'SNR_dB', 200,...
        'numPulses', 256);
    radar.run();
    PSLR_dB(i) = radar.measurePSLR();
end

figure(1)
clf;
plot(targetRange, PSLR_dB, LineWidth=1.5);

 % Label Plot
            title('Peak Sidelobe Ratio vs Range')
            %legend('Signal Power', 'Average Power');
            xlabel('Range (m)');
            ylabel('PSLR (dB)');
            grid on;
%% OFDM Radar (Target at Large Range);
radar = ofdmRadar(...
    'nDataCarriers', 49,...
    'nullDcSubcarrier', false,...
    'targetRange', 50);
radar.run();

%% OFDM Radar (Target at Even Larger Range);
radar = ofdmRadar(...
    'nDataCarriers', 49,...
    'nullDcSubcarrier', false,...
    'targetRange', 1000);
radar.run();

%% OFDM Radar Improved Parameters
radar = ofdmRadar(...
    'carrierFreq', 77e9,...
    'targetRange', 50,...
    'targetVelocity', 50,...
    'sampleRate', 200e6,...
    'nSubcarriers', 16*64,...
    'nDataCarriers', 16*48+1,...
    'nPilotCarriers', 16*4,...
    'autoplacePilots', true,...
    'nullDcSubcarrier', false,...
    'numPulses', 128);
radar.run();