%% Run OFDM Model using 802.11a pilots and AWGN channel
o = ofdmModel('nSymbols', 1e5);
o.run();

%% Run OFDM Model using 802.11a pilots and Rayleigh channel
o = ofdmModel(...
       'nSymbols', 1e5,...
    'enRayleighFading', true,...
    'eqAlgorithm', 'mmse');
o.run();

%% Run OFDM Model using 802.11a pilots and Rayleigh channel
o = ofdmModel(...
    'sampleRate', 320e6,...
    'nSubcarriers', 32*64,...
    'nDataCarriers', 32*48+1,...
    'nPilotCarriers', 32*4,...
    'autoplacePilots', true,...
    'nullDcSubcarrier', false,...
    'nSymbols', 1e4,...
    'enRayleighFading', false,...
    'eqAlgorithm', 'mmse');
o.run();