%% Run OFDM Model using 802.11a pilots and AWGN channel
o = ofdmModel('nSymbols', 1e5);
o.run();

%% Run OFDM Model using 802.11a pilots and Rayleigh channel
o = ofdmModel(...
       'nSymbols', 1e5,...
    'enRayleighFading', true,...
    'eqAlgorithm', 'mmse');
o.run();

%% Run OFDM Model using 802.11a pilots and Rayleigh channel
o = ofdmModel(...
    'sampleRate', 200e6,...
    'nSubcarriers', 16*64,...
    'nDataCarriers', 16*48+1,...
    'nPilotCarriers', 16*4,...
    'autoplacePilots', true,...
    'nullDcSubcarrier', false,...
    'nSymbols', 1e5,...
    'enRayleighFading', false,...
    'eqAlgorithm', 'mmse');
o.run();